lib/laughing_octo_invention_web/router.ex
defmodule LaughingOctoInventionWeb.Router do
  use LaughingOctoInventionWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    # plug :put_root_layout, {LaughingOctoInventionWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LaughingOctoInventionWeb do
    pipe_through :browser

    get "/", StaticPageController, :home, as: :root
    get "/help", StaticPageController, :help, as: :help
    get "/about", StaticPageController, :about, as: :about
    get "/contact", StaticPageController, :contact, as: :contact
    get "/signup", UserController, :new, as: :signup
  end

  # Other scopes may use custom stacks.
  # scope "/api", LaughingOctoInventionWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LaughingOctoInventionWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/laughing_octo_invention/application.ex
defmodule LaughingOctoInvention.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      LaughingOctoInvention.Repo,
      # Start the Telemetry supervisor
      LaughingOctoInventionWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: LaughingOctoInvention.PubSub},
      # Start the Endpoint (http/https)
      LaughingOctoInventionWeb.Endpoint
      # Start a worker by calling: LaughingOctoInvention.Worker.start_link(arg)
      # {LaughingOctoInvention.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: LaughingOctoInvention.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    LaughingOctoInventionWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/laughing_octo_invention/mailer.ex
defmodule LaughingOctoInvention.Mailer do
  use Swoosh.Mailer, otp_app: :laughing_octo_invention
end

lib/laughing_octo_invention/repo.ex
defmodule LaughingOctoInvention.Repo do
  use Ecto.Repo,
    otp_app: :laughing_octo_invention,
    adapter: Ecto.Adapters.Postgres
end

lib/laughing_octo_invention_web/controllers/static_page_controller.ex
defmodule LaughingOctoInventionWeb.StaticPageController do
  use LaughingOctoInventionWeb, :controller

  def root(conn, _params) do
    render(conn, "home.html")
  end

  def home(conn, _params) do
    render(conn, "home.html")
  end

  def help(conn, _params) do
    render(conn, "help.html")
  end

  def about(conn, _params) do
    render(conn, "about.html")
  end

  def contact(conn, _params) do
    render(conn, "contact.html")
  end
end

lib/laughing_octo_invention_web/controllers/user_controller.ex
defmodule LaughingOctoInventionWeb.UserController do
  use LaughingOctoInventionWeb, :controller

  def new(conn, _params) do
    render(conn, "new.html")
  end
end

lib/laughing_octo_invention_web/views/error_view.ex
defmodule LaughingOctoInventionWeb.ErrorView do
  use LaughingOctoInventionWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/laughing_octo_invention_web/views/layout_view.ex
defmodule LaughingOctoInventionWeb.LayoutView do
  use LaughingOctoInventionWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/laughing_octo_invention_web/views/static_page_view.ex
defmodule LaughingOctoInventionWeb.StaticPageView do
  use LaughingOctoInventionWeb, :view
end

lib/laughing_octo_invention_web/views/user_view.ex
defmodule LaughingOctoInventionWeb.UserView do
  use LaughingOctoInventionWeb, :view
end

lib/laughing_octo_invention_web/templates/layout/_footer.html.heex
<footer class="footer">
    <div class="container">
      <small>
        The <a href="#">Phoenix Tutorial</a>
        as done by <a href="#">Robert Gouge</a>
      </small>
      <nav>
        <ul>
          <li><%= link "About", to: Routes.about_path(@conn, :about) %></li>
          <li><%= link "Contact", to: Routes.contact_path(@conn, :contact) %></li>
        </ul>
      </nav>
    </div>
  </footer>

lib/laughing_octo_invention_web/templates/layout/_header.html.heex
<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link "sample app", to: Routes.root_path(@conn, :home) , id: "logo", class: "navbar-brand" %>
        <button class="navbar-toggler" type="button"
        data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false"
        aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ms-auto" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <%= link "Home", to: Routes.root_path(@conn, :home) , class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "Help", to: Routes.help_path(@conn, :help) , class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "Log in", to: "#" , class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

lib/laughing_octo_invention_web/templates/layout/app.html.heex
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= LaughingOctoInventionWeb.DynamicTextHelpers.page_title(Enum.into(assigns,
      %{view_module: @conn.private.phoenix_view, action:
      @conn.private.phoenix_action})) %>
    </title>
    <link rel="stylesheet"
    href={Routes.static_path(@conn, "/assets/app.css")} />
  </head>
  <body>
    <%= render "_header.html", assigns %>

  <div class="container mt-4">
    <%= @inner_content %>
    <%= render "_footer.html", assigns %>
  </div>
  <script type="text/javascript"
  src={ Routes.static_path(@conn, "/assets/app.js")}></script>
  </body>
</html>

lib/laughing_octo_invention_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/laughing_octo_invention_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "LaughingOctoInvention", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/laughing_octo_invention_web/templates/static_page/about.html.heex
<h1>About</h1>
<p>
    The <a href="#"><em>Phoenix
            Tutorial</em></a> is a
    <a href="#">book</a>
    to teach web development with
    <a href="https://phoenixframework.org/">Phoenix</a>.
    This is the sample application for the tutorial.
</p>

lib/laughing_octo_invention_web/templates/static_page/contact.html.heex
<h1>Contact</h1>
<p>
  Contact the Phoenix Tutorial about the sample app at the
  <a href="#">contact page</a>.
</p>

lib/laughing_octo_invention_web/templates/static_page/help.html.heex
<h1>Help</h1>
<p>
    Get help on the Phoenix Tutorial at the
    <a href="#">Phoenix Tutorial help page</a>.
    To get help on this sample app, see the
    <a href="#"><em>Phoenix Tutorial</em>
        book</a>.
</p>

lib/laughing_octo_invention_web/templates/static_page/home.html.heex
<div class="hero-container container-fluid rounded p-5 mb-4">
    <div class="container text-center p-5">
      <h1>Welcome to the Sample App</h1>
      <h2>
        This is the home page for the
        <a href="#">Phoenix Tutorial</a>
        sample application.
      </h2>
      <%= link "Sign up now!", to: Routes.signup_path(@conn, :new),
      class: "btn btn-lg btn-primary" %>  
    </div>
  </div>
  <%= link img_tag(Routes.static_path(@conn, "/images/phoenix.png"),
    alt: "Phoenix logo", width: 260, height: 40),
    to: "https://phoenixframework.org/" %>

lib/laughing_octo_invention_web/templates/user/new.html.heex
<h1>User#new</h1>
<p>Find me in lib/sample_app_web/templates/user/new.html.heex</p>